name: tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r dali2mqtt/requirements-dev.txt
      - name: Run tests
        working-directory: dali2mqtt
        run: python -m pytest
